### ISSUE TITLE
Convert props from kebab-case to camelCase

### ISSUE THREAD

**Issue by thewebartisan7** [thewebartisan7/posthtml-components#15]
When component has:

```html
<x-component my-local="I am local"></x-component>
```

Then the prop can be accessed using:

```html
<div>{{ myLocal }}</div>
```

**Comment by thewebartisan7** [comment]
There is no way to know if an attribute is a local or an attribute to be passed to component, so for now closing this.

**Comment by cossssmin** [comment]
Just ran into this today, I think the `:` prefix I was mentioning in #24 could help differentiate between the two.

**Comment by thewebartisan7** [comment]
Yes right using the prefix would solve also this issue, however with prefix ":" we have the issue mentioned here https://github.com/thewebartisan7/posthtml-components/issues/24#issuecomment-1330104115

And also we will not solve compatibility with posthtml-modules since usage of component would change, see https://github.com/thewebartisan7/posthtml-components/issues/24#issuecomment-1330419704
