### ISSUE TITLE
Define props as functions

### ISSUE THREAD

**Issue by cossssmin** [thewebartisan7/posthtml-components#25]
Tried doing this but it just returns the fallback, am I missing something?

`alert.html` component:

```js
<script props>
  module.exports = {
    type: ({type} = props) => {
      return type || 'info';
    }
  }
</script>

<div class="{{ type }}">
  <content></content>
</div>
```

Use it:

```html
<x-alert type="danger">Danger</x-alert>
```

Result:

```html
<div class="info">
  Danger
</div>
```

Expected:

```diff
- <div class="info">
+ <div class="danger">
  Danger
</div>
```

**Comment by thewebartisan7** [comment]
You are defining `type` as function, then you have to call that function like:

```diff
- <div class="{{ type }}">
+ <div class="{{ type() }}">
  <content></content>
</div>

{{ typeof type === 'function' ? 'yes' : 'no' }} // print yes
```

Or you can make a self-invoking function like:

```html
<script props>
  module.exports = {
    type: (({type} = props) => {
      return type || 'info';
    })()
  }
</script>

<!-- Now type is a string and not a function -->
<div class="{{ type }}">
  <content></content>
</div>
```

However, it's really strange your output. The function it's like called but without arguments, I would rather expect that it return whole function as string like here:

https://jsfiddle.net/36dzgjxk/

**Comment by thewebartisan7** [comment]
It's seem like it's get executed as [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)  

See update here https://jsfiddle.net/q82mhbo6/

```js
const props = {
	type: 'danger'
}

const fn = ({type} = props) => {
  return type || 'info';
}


console.log(fn()); // correct output
console.log(fn``); // output default "info"
```

**Comment by thewebartisan7** [comment]
Anyway not sure what you are trying to archive, maybe is just starting, but why not just:

```html
<script props>
  module.exports = {
    type: type || 'info'
  }
</script>

<div class="{{ type }}">
  <content></content>
</div>
```

Or in this case I also use objects like:

```html
<script props>
  module.exports = {
    type: {
      info: 'alert-info',
      danger: 'alert-danger'
    }[props.type] || 'alert-info'
  }
</script>
```

So you can avoid to type whole class name and use nicer API for your component.

**Comment by cossssmin** [comment]
The `type` value would be used as a condition to render different classes, I had that removed from my example for brevity.

So I initially imagined it like this:

```js
<script props>
  module.exports = {
    type: ({type} = props) => {
      switch (type) {
        case 'danger':
          return 'bg-red-100 text-red-700';
          break;
        case 'warning':
          return 'bg-yellow-100 text-yellow-700';
          break;
        case 'info':
        default:
          return 'bg-blue-100 text-blue-700';
          break;
      }
    }
  }
</script>
```

Your last example does the trick and I could use that, yes, but in reality there may be various reasons for which you'd need to use a method's return value instead :)

**Comment by thewebartisan7** [comment]
I see now what you are trying to archive.

In that example I would just create an object with type as key and classes as value.

Or if you are doing some more computation, then move the function outside the exports, like:

```html
<script props>

    const getType = ({type} = props) => {
      switch (type) {
        case 'danger':
          return 'bg-red-100 text-red-700';
          break;
        case 'warning':
          return 'bg-yellow-100 text-yellow-700';
          break;
        case 'info':
        default:
          return 'bg-blue-100 text-blue-700';
          break;
      }
   };

  module.exports = {
    type: getType()
  }
</script>
```

Or just call the function in template or as self-invoking function shown here https://github.com/thewebartisan7/posthtml-components/issues/25#issuecomment-1337729272

**Comment by cossssmin** [comment]
You're right, I should just define the function and call it like that. Thanks for the help :)
