### ISSUE TITLE
`options.elementAttributes` does not work

### ISSUE THREAD

**Issue by cossssmin** [thewebartisan7/posthtml-components#28]
Looks like `(tagName, modifier)` should be used the other way around here:

https://github.com/thewebartisan7/posthtml-components/blob/67f554ea204dac1bda1ac130af2c51d707f7670c/src/process-attributes.js#L53-L64

If you `console.log(tagName, modifier)` just before `const attributes = ...`, you'll see the values are swapped. So `modifier` is the tag name (string, i.e. `DIV`, and the `tagName` is the function, i.e. `[Function: DIV]`.

**Comment by thewebartisan7** [comment]
ops... [You are right](https://lodash.com/docs/4.17.15#forEach) 

I just realize now that I didn't write test for this new options.

Thanks for your testing, I will write some tests for this and fix code.

**Comment by thewebartisan7** [comment]
Fixed and test added https://github.com/thewebartisan7/posthtml-components/commit/2d737dcb8e563a0e737f0325de3e9bd62d98e235

**Comment by cossssmin** [comment]
Thanks, this works well now 👍
