### ISSUE TITLE
Two tests fail when installing using yarn

### ISSUE THREAD

**Issue by thewebartisan7** [thewebartisan7/posthtml-components#34]
```
  attributes › Must remove an attributes that has "undefined" or "null" value
  locals › Must process components with invalid script file

  ReferenceError {
    message: '\'target\' is not defined',
  }
 ReferenceError {
    message: '\'myProp\' is not defined',
  }
```

**Comment by thewebartisan7** [comment]
This seem to happen only after installing with yarn, see https://github.com/thewebartisan7/posthtml-components/issues/33

**Comment by Ulyanov-programmer** [comment]
Strange. When I installed via yarn in the usual way (_with node_modules, without zero installation_), everything worked stably.

**Comment by thewebartisan7** [comment]
Yes it worked also for me, apart this two tests that fail.
