### ISSUE TITLE
The plugin should be the first in the queue.

### ISSUE THREAD

**Issue by Ulyanov-programmer** [thewebartisan7/posthtml-components#35]
This is not a mistake, but an important aspect.

The plugin interferes with the work of other posthtml plugins (they simply do not work), so that this does not happen, it must be the **first** in the queue of posthtml plugins.

_This is worth mentioning in the documentation._

**Comment by thewebartisan7** [comment]
This is not always the case. Some times it may be required to be the first, other times not. Some times it might be required that other plugins are run before and after. It depends on the structure of the HTML files.

For example in this case [here](https://github.com/thewebartisan7/posthtml-components/issues/21#issuecomment-1328278572) it is better that the fetchPlugin is executed first.

You can also pass your plugins via `options.plugins` as an array, and this will be executed for each component file (even nested).

The only limitation for now is that doesn't support async plugins as reported in this [issue](https://github.com/thewebartisan7/posthtml-components/issues/21). I will add support for async plugin as soon as I get time to check into.

**Comment by Ulyanov-programmer** [comment]
Even so!
Thanks for the prompt clarification, but still think about whether it is worth displaying in the documentation.

**Comment by thewebartisan7** [comment]
Yes I agree, docs can be improved. Not only for this, but also for others things. Some more advanced features or edge cases are not even documented. I will take note for this and add it ASAP. Thanks for your input.
