### ISSUE TITLE
Cannot load additional plugins with Parcel .posthtmlrc file

### ISSUE THREAD

**Issue by reimar** [thewebartisan7/posthtml-components#37]
Hi. Thank you so much for developing this great plugin. I have a problem and hope you can help me out.

* I would like to use _posthtml-include_ with _posthtml-components_
* I am using [Parcel](https://parceljs.org) with a .posthtmlrc file for configuration:

```json
{
  "plugins": {
    "posthtml-include": {},
    "posthtml-extend": {},
    "posthtml-markdownit": {},
    "posthtml-component": {
      "root": "./src",
      "folders": ["components"],
      "plugins": ["posthtml-include"]
    }
  }
}
```

Unfortunately, this throws an error: `@parcel/transformer-posthtml: plugin is not a function`. What am I missing?

**Comment by reimar** [comment]
And shortly after posting I found a solution myself, argh. I can use a JavaScript config file instead (although Parcel disencourages doing so):

```js
module.exports = {
  plugins: {
    'posthtml-include': {},
    'posthtml-extend': {},
    'posthtml-markdownit': {},
    'posthtml-component': {
      root: './src',
      folders: ['components'],
      plugins: [require('posthtml-include')({})],
    },
  },
};
```

However, is there a way to support additional plugins when using a .posthtmlrc file for configuration? I guess that would be a feature-request then.

**Comment by cossssmin** [comment]
I'm curious, what's your use-case for `posthtml-include` when you can already do everything it does with this plugin?

**Comment by reimar** [comment]
Sure :)

In my case I have components which include SVG icons. Since I want to style and even animate them, I need the inline the SVG code. For example inside a button:

```html
[...]

<button>
    <span class="button_icon">
        <include src="./node_modules/lucide-static/icons/{{ icon }}.svg"></include>
    </span>
    <span class="button_label">{{ label }}</span>
</button>
```

**Comment by reimar** [comment]
Wow, thank you @thewebartisan7 !

I tried all your examples with my setup and I can confirm that they work perfectly. I actually also tried to require the files directly via readFileSync before but couldn’t get it to work and eventually gave up. I was so close — `require.resolve` does the trick 🤦! 

So I think to create a primitive `<x-icon>` component is actually the most elegant and versatile solution.

Again, thank you for taking the time for this. Cheers!

**Comment by thewebartisan7** [comment]
> I actually also tried to require the files directly via readFileSync before but couldn’t get it to work and eventually gave up.

Yes me too first time. Then I found the `require.resolve` API, which “use(es) the internal require() machinery to look up the location of a module, but rather than loading the module, just return(s) the resolved filename.” (quote from nodejs doc)

**Comment by reimar** [comment]
Also thank you @cossssmin ! It’s perfectly true that there is no need to use _posthtml-include_ in combination with _posthtml-components_, it is even clearly [stated in the documentation](https://github.com/thewebartisan7/posthtml-components#tag-names-and-x-tags). Somehow I must have skipped that.
